app:
    name: Hospital Service
server:
    port: 8080
    
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhoirkarsukhdeo95@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          transport:
            protocol: smtp
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/video_streaming_app
    username:  root
    password:  root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update    
    database: MYSQL
  
